-- Attendance table for admin-only attendance management.
create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  member_ref bigint not null references public.members(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('present', 'late', 'absent', 'excused')),
  check_in_time time,
  check_out_time time,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_records_unique_member_date unique (member_ref, attendance_date),
  constraint attendance_records_time_order check (
    check_in_time is null
    or check_out_time is null
    or check_out_time >= check_in_time
  )
);

create index if not exists attendance_records_attendance_date_idx
  on public.attendance_records (attendance_date desc);
create index if not exists attendance_records_member_ref_idx
  on public.attendance_records (member_ref);
create index if not exists attendance_records_status_idx
  on public.attendance_records (status);

create or replace function public.set_attendance_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_records_updated_at on public.attendance_records;
create trigger trg_attendance_records_updated_at
before update on public.attendance_records
for each row
execute function public.set_attendance_records_updated_at();

alter table public.attendance_records enable row level security;

-- Admin-only access. Assumes existing profiles table with columns:
-- profiles.id = auth.uid() and profiles.role = 'admin'
drop policy if exists attendance_records_select_admin on public.attendance_records;
create policy attendance_records_select_admin
on public.attendance_records
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_records_insert_admin on public.attendance_records;
create policy attendance_records_insert_admin
on public.attendance_records
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_records_update_admin on public.attendance_records;
create policy attendance_records_update_admin
on public.attendance_records
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_records_delete_admin on public.attendance_records;
create policy attendance_records_delete_admin
on public.attendance_records
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);
