-- Holiday columns for attendance grid (admin-only).
create table if not exists public.attendance_holidays (
  id bigint generated by default as identity primary key,
  holiday_date date not null unique,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists attendance_holidays_date_idx
  on public.attendance_holidays (holiday_date);

create or replace function public.set_attendance_holidays_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_holidays_updated_at on public.attendance_holidays;
create trigger trg_attendance_holidays_updated_at
before update on public.attendance_holidays
for each row
execute function public.set_attendance_holidays_updated_at();

alter table public.attendance_holidays enable row level security;

drop policy if exists attendance_holidays_select_admin on public.attendance_holidays;
create policy attendance_holidays_select_admin
on public.attendance_holidays
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_holidays_insert_admin on public.attendance_holidays;
create policy attendance_holidays_insert_admin
on public.attendance_holidays
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_holidays_update_admin on public.attendance_holidays;
create policy attendance_holidays_update_admin
on public.attendance_holidays
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_holidays_delete_admin on public.attendance_holidays;
create policy attendance_holidays_delete_admin
on public.attendance_holidays
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);
