-- Recurring yearly BS holiday templates (admin-only).
create table if not exists public.attendance_holiday_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  bs_month int not null check (bs_month between 0 and 11),
  bs_day int not null check (bs_day between 1 and 32),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_holiday_templates_unique unique (name, bs_month, bs_day)
);

create index if not exists attendance_holiday_templates_month_day_idx
  on public.attendance_holiday_templates (bs_month, bs_day);

create or replace function public.set_attendance_holiday_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_attendance_holiday_templates_updated_at on public.attendance_holiday_templates;
create trigger trg_attendance_holiday_templates_updated_at
before update on public.attendance_holiday_templates
for each row
execute function public.set_attendance_holiday_templates_updated_at();

alter table public.attendance_holiday_templates enable row level security;

drop policy if exists attendance_holiday_templates_select_admin on public.attendance_holiday_templates;
create policy attendance_holiday_templates_select_admin
on public.attendance_holiday_templates
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_holiday_templates_insert_admin on public.attendance_holiday_templates;
create policy attendance_holiday_templates_insert_admin
on public.attendance_holiday_templates
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_holiday_templates_update_admin on public.attendance_holiday_templates;
create policy attendance_holiday_templates_update_admin
on public.attendance_holiday_templates
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists attendance_holiday_templates_delete_admin on public.attendance_holiday_templates;
create policy attendance_holiday_templates_delete_admin
on public.attendance_holiday_templates
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);
