-- Stores progress report email send history.
create table if not exists public.member_report_logs (
  id bigint generated by default as identity primary key,
  member_ref bigint not null references public.members(id) on delete cascade,
  recipient_email text,
  status text not null check (status in ('sent', 'failed')),
  error_message text,
  sent_by uuid,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists member_report_logs_member_ref_idx
  on public.member_report_logs (member_ref, sent_at desc);

alter table public.member_report_logs enable row level security;

drop policy if exists member_report_logs_select_admin on public.member_report_logs;
create policy member_report_logs_select_admin
on public.member_report_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_report_logs_insert_admin on public.member_report_logs;
create policy member_report_logs_insert_admin
on public.member_report_logs
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_report_logs_update_admin on public.member_report_logs;
create policy member_report_logs_update_admin
on public.member_report_logs
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_report_logs_delete_admin on public.member_report_logs;
create policy member_report_logs_delete_admin
on public.member_report_logs
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);
