-- Members table for admin-only member management and CSV import.
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  member_id text not null unique,
  full_name text not null,
  email text,
  phone text not null,
  membership_type text not null check (membership_type in ('monthly', 'quarterly', 'yearly', 'trial')),
  membership_status text not null check (membership_status in ('active', 'paused', 'cancelled', 'expired')),
  start_date date,
  end_date date,
  last_visit_date date,
  payment_status text not null check (payment_status in ('paid', 'unpaid', 'overdue')),
  payment_due_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_updated_at_idx on public.members (updated_at desc);
create index if not exists members_membership_status_idx on public.members (membership_status);
create index if not exists members_payment_status_idx on public.members (payment_status);

create or replace function public.set_members_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_members_updated_at on public.members;
create trigger trg_members_updated_at
before update on public.members
for each row
execute function public.set_members_updated_at();

alter table public.members enable row level security;

-- Admin-only access. Assumes existing profiles table with columns:
-- profiles.id = auth.uid() and profiles.role = 'admin'
drop policy if exists members_select_admin on public.members;
create policy members_select_admin
on public.members
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists members_insert_admin on public.members;
create policy members_insert_admin
on public.members
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists members_update_admin on public.members;
create policy members_update_admin
on public.members
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists members_delete_admin on public.members;
create policy members_delete_admin
on public.members
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

