-- Body measurements per member.
create table if not exists public.member_measurements (
  id bigint generated by default as identity primary key,
  member_ref bigint not null references public.members(id) on delete cascade,
  recorded_at date not null,
  weight_kg numeric(6,2),
  body_fat_percent numeric(5,2),
  chest_cm numeric(6,2),
  waist_cm numeric(6,2),
  hips_cm numeric(6,2),
  arm_cm numeric(6,2),
  thigh_cm numeric(6,2),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists member_measurements_member_ref_idx
  on public.member_measurements (member_ref, recorded_at desc);

alter table public.member_measurements enable row level security;

drop policy if exists member_measurements_select_admin on public.member_measurements;
create policy member_measurements_select_admin
on public.member_measurements
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_measurements_insert_admin on public.member_measurements;
create policy member_measurements_insert_admin
on public.member_measurements
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_measurements_update_admin on public.member_measurements;
create policy member_measurements_update_admin
on public.member_measurements
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_measurements_delete_admin on public.member_measurements;
create policy member_measurements_delete_admin
on public.member_measurements
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- Transformation timeline per member (photo url + milestone).
create table if not exists public.member_transformations (
  id bigint generated by default as identity primary key,
  member_ref bigint not null references public.members(id) on delete cascade,
  captured_at date not null,
  milestone_title text,
  milestone_notes text,
  photo_url text,
  created_at timestamptz not null default now()
);

create index if not exists member_transformations_member_ref_idx
  on public.member_transformations (member_ref, captured_at desc);

alter table public.member_transformations enable row level security;

drop policy if exists member_transformations_select_admin on public.member_transformations;
create policy member_transformations_select_admin
on public.member_transformations
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_transformations_insert_admin on public.member_transformations;
create policy member_transformations_insert_admin
on public.member_transformations
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_transformations_update_admin on public.member_transformations;
create policy member_transformations_update_admin
on public.member_transformations
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists member_transformations_delete_admin on public.member_transformations;
create policy member_transformations_delete_admin
on public.member_transformations
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);
