-- Monthly Membership Fee Tracking System
-- Tracks monthly membership fees, due dates, and payment history per member

-- Table to track monthly membership fee periods and payments
CREATE TABLE IF NOT EXISTS public.membership_fees (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    billing_month date NOT NULL, -- First day of the billing month (e.g., '2026-09-01' for September 2026)
    amount_minor bigint NOT NULL DEFAULT 0,
    currency_code text NOT NULL DEFAULT 'NPR',
    status text NOT NULL DEFAULT 'unpaid', -- 'paid', 'unpaid', 'overdue', 'partial'
    paid_amount_minor bigint NOT NULL DEFAULT 0,
    due_date date NOT NULL,
    paid_at timestamp with time zone,
    paid_by uuid,
    invoice_id bigint REFERENCES public.invoices(id) ON DELETE SET NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT membership_fees_status_check CHECK (status IN ('paid', 'unpaid', 'overdue', 'partial')),
    CONSTRAINT membership_fees_amount_check CHECK (amount_minor >= 0),
    CONSTRAINT membership_fees_paid_check CHECK (paid_amount_minor >= 0 AND paid_amount_minor <= amount_minor),
    UNIQUE (member_id, billing_month)
);

ALTER TABLE public.membership_fees OWNER TO postgres;

CREATE INDEX IF NOT EXISTS membership_fees_member_id_idx ON public.membership_fees (member_id);
CREATE INDEX IF NOT EXISTS membership_fees_billing_month_idx ON public.membership_fees (billing_month);
CREATE INDEX IF NOT EXISTS membership_fees_status_idx ON public.membership_fees (status);
CREATE INDEX IF NOT EXISTS membership_fees_due_date_idx ON public.membership_fees (due_date);

-- Function to calculate the next month's first day (handles month-end dates)
CREATE OR REPLACE FUNCTION public.next_month_first_day(p_date date)
RETURNS date LANGUAGE sql IMMUTABLE AS $$
    SELECT date_trunc('month', (p_date + interval '1 month'))::date
$$;

-- Function to safely add months preserving day (e.g., Jan 31 -> Feb 28/29)
CREATE OR REPLACE FUNCTION public.add_months_preserving_day(p_date date, p_months integer)
RETURNS date LANGUAGE plpgsql AS $$
DECLARE
    v_result date;
    v_day integer;
BEGIN
    v_day := EXTRACT(DAY FROM p_date);
    v_result := (date_trunc('month', p_date) + (p_months || ' months')::interval)::date;
    -- Try to set the same day, fallback to last day of month
    BEGIN
        v_result := v_result + (v_day - 1) * interval '1 day';
    EXCEPTION WHEN datetime_field_overflow THEN
        -- Day doesn't exist in target month, use last day
        v_result := (date_trunc('month', v_result) + interval '1 month - 1 day')::date;
    END;
    RETURN v_result;
END $$;

-- Function to initialize membership fees for a new member
-- Creates fee records for all months from start_date to end_date (or current month if no end_date)
CREATE OR REPLACE FUNCTION public.initialize_membership_fees(p_member_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_member RECORD;
    v_start_date date;
    v_end_date date;
    v_current_month date;
    v_amount_minor bigint;
    v_plan_price text;
    v_currency_code text;
BEGIN
    -- Get member details
    SELECT m.*, s.currency_code
    INTO v_member
    FROM public.members m
    CROSS JOIN public.admin_settings s
    WHERE m.id = p_member_id AND s.id = 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Member not found';
    END IF;

    -- Get plan price from pricing_items
    SELECT price INTO v_plan_price
    FROM public.pricing_items
    WHERE kind = 'plan' AND title ILIKE v_member.membership_type AND is_active = true
    ORDER BY sort_order LIMIT 1;

    IF v_plan_price IS NOT NULL THEN
        -- Parse price string to minor units (assuming format like "5000" or "5,000")
        v_amount_minor := regexp_replace(v_plan_price, '[^\d.]', '', 'g')::numeric * 100;
    ELSE
        v_amount_minor := 0;
    END IF;

    v_currency_code := v_member.currency_code;
    v_start_date := v_member.start_date;
    v_end_date := v_member.end_date;

    -- If no start_date, use created_at date
    IF v_start_date IS NULL THEN
        v_start_date := v_member.created_at::date;
    END IF;

    -- If no end_date, use current month
    IF v_end_date IS NULL THEN
        v_end_date := date_trunc('month', public.get_nepal_today_ad())::date;
    END IF;

    -- Round start_date to first day of month
    v_current_month := date_trunc('month', v_start_date)::date;

    -- Create fee records for each month
    WHILE v_current_month <= date_trunc('month', v_end_date)::date LOOP
        INSERT INTO public.membership_fees (member_id, billing_month, amount_minor, currency_code, status, due_date)
        VALUES (
            p_member_id,
            v_current_month,
            v_amount_minor,
            v_currency_code,
            CASE WHEN v_current_month <= date_trunc('month', public.get_nepal_today_ad())::date THEN 'unpaid' ELSE 'unpaid' END,
            public.add_months_preserving_day(v_current_month, 0) -- Due on the same date of the month
        )
        ON CONFLICT (member_id, billing_month) DO NOTHING;

        v_current_month := public.next_month_first_day(v_current_month);
    END LOOP;

    -- Update member's payment_due_date to the earliest unpaid fee's due_date
    UPDATE public.members
    SET payment_due_date = (
        SELECT MIN(due_date) FROM public.membership_fees
        WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
    )
    WHERE id = p_member_id;
END $$;

-- Function to record a membership fee payment
CREATE OR REPLACE FUNCTION public.record_membership_fee_payment(
    p_fee_id bigint,
    p_amount_minor bigint,
    p_payment_method text,
    p_payment_date date DEFAULT NULL,
    p_reference text DEFAULT NULL,
    p_notes text DEFAULT NULL
)
RETURNS public.membership_fees LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_fee RECORD;
    v_new_paid_amount bigint;
    v_new_status text;
    v_invoice_id bigint;
    v_member_id bigint;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Admin access required';
    END IF;

    IF p_amount_minor <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be positive';
    END IF;

    SELECT * INTO v_fee FROM public.membership_fees WHERE id = p_fee_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Membership fee not found';
    END IF;

    IF v_fee.paid_amount_minor + p_amount_minor > v_fee.amount_minor THEN
        RAISE EXCEPTION 'Payment exceeds outstanding amount';
    END IF;

    v_new_paid_amount := v_fee.paid_amount_minor + p_amount_minor;
    v_new_status := CASE
        WHEN v_new_paid_amount >= v_fee.amount_minor THEN 'paid'
        WHEN v_new_paid_amount > 0 THEN 'partial'
        ELSE v_fee.status
    END;

    -- Update the fee record
    UPDATE public.membership_fees
    SET paid_amount_minor = v_new_paid_amount,
        status = v_new_status,
        paid_at = CASE WHEN v_new_status = 'paid' THEN now() ELSE paid_at END,
        paid_by = CASE WHEN v_new_status = 'paid' THEN auth.uid() ELSE paid_by END,
        updated_at = now()
    WHERE id = p_fee_id
    RETURNING * INTO v_fee;

    -- Update member's payment_due_date to next unpaid fee
    UPDATE public.members
    SET payment_due_date = (
        SELECT MIN(due_date) FROM public.membership_fees
        WHERE member_id = v_fee.member_id AND status IN ('unpaid', 'overdue', 'partial')
    ),
    payment_status = CASE
        WHEN EXISTS (
            SELECT 1 FROM public.membership_fees
            WHERE member_id = v_fee.member_id AND status IN ('unpaid', 'overdue', 'partial')
        ) THEN 'unpaid'
        ELSE 'paid'
    END,
    updated_at = now()
    WHERE id = v_fee.member_id;

    RETURN v_fee;
END $$;

-- Function to mark overdue fees (can be run via cron or manually)
CREATE OR REPLACE FUNCTION public.update_overdue_membership_fees()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_today date := public.get_nepal_today_ad();
    v_count integer := 0;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Admin access required';
    END IF;

    UPDATE public.membership_fees
    SET status = 'overdue',
        updated_at = now()
    WHERE status IN ('unpaid', 'partial')
      AND due_date < v_today;

    GET DIAGNOSTICS v_count = ROW_COUNT;

    -- Also update member payment_status
    UPDATE public.members m
    SET payment_status = 'overdue',
        updated_at = now()
    WHERE EXISTS (
        SELECT 1 FROM public.membership_fees mf
        WHERE mf.member_id = m.id AND mf.status = 'overdue'
    )
    AND m.payment_status != 'overdue'
    AND m.deleted_at IS NULL;

    RETURN v_count;
END $$;

-- Function to get member's membership fee summary
CREATE OR REPLACE FUNCTION public.get_membership_fee_summary(p_member_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_summary jsonb;
BEGIN
    SELECT jsonb_build_object(
        'total_due', COALESCE(SUM(CASE WHEN status IN ('unpaid', 'overdue', 'partial') THEN amount_minor - paid_amount_minor ELSE 0 END), 0),
        'total_paid', COALESCE(SUM(paid_amount_minor), 0),
        'overdue_count', COUNT(*) FILTER (WHERE status = 'overdue'),
        'unpaid_count', COUNT(*) FILTER (WHERE status = 'unpaid'),
        'partial_count', COUNT(*) FILTER (WHERE status = 'partial'),
        'paid_count', COUNT(*) FILTER (WHERE status = 'paid'),
        'next_due_date', (
            SELECT MIN(due_date) FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
        ),
        'next_due_amount', (
            SELECT amount_minor - paid_amount_minor FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
            ORDER BY due_date LIMIT 1
        ),
        'next_due_month', (
            SELECT billing_month FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
            ORDER BY due_date LIMIT 1
        ),
        'currency_code', (
            SELECT currency_code FROM public.membership_fees
            WHERE member_id = p_member_id LIMIT 1
        )
    ) INTO v_summary
    FROM public.membership_fees
    WHERE member_id = p_member_id;

    RETURN COALESCE(v_summary, jsonb_build_object(
        'total_due', 0, 'total_paid', 0, 'overdue_count', 0, 'unpaid_count', 0,
        'partial_count', 0, 'paid_count', 0, 'next_due_date', null,
        'next_due_amount', null, 'next_due_month', null, 'currency_code', 'NPR'
    ));
END $$;

-- Function to record multi-month membership fee payment
-- Creates an invoice for the selected months and marks them as paid
CREATE OR REPLACE FUNCTION public.record_membership_fee_payment_multi(
    p_fee_ids bigint[],
    p_payment_method text,
    p_payment_date date DEFAULT NULL,
    p_reference text DEFAULT NULL,
    p_notes text DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_fees RECORD;
    v_fee_ids bigint[];
    v_total_amount bigint := 0;
    v_total_paid bigint := 0;
    v_invoice_id bigint;
    v_member_id bigint;
    v_last_paid_month date;
    v_billing_months text[] := '{}';
    v_fee_data jsonb[] := '{}';
    v_settings RECORD;
    v_invoice_number text;
    v_today date := public.get_nepal_today_ad();
    v_prefix text;
    v_seq bigint;
    v_year int;
    v_number text;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Admin access required';
    END IF;

    IF p_fee_ids IS NULL OR array_length(p_fee_ids, 1) = 0 THEN
        RAISE EXCEPTION 'No fee periods selected';
    END IF;

    IF p_payment_method NOT IN ('cash','card','bank_transfer','digital_wallet','other') THEN
        RAISE EXCEPTION 'Invalid payment method';
    END IF;

    -- Get admin settings for invoice numbering
    SELECT * INTO v_settings FROM public.admin_settings WHERE id = 1;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Admin settings not found';
    END IF;
    v_prefix := v_settings.invoice_prefix;

    -- Get and lock the selected fees, verify they belong to same member and are unpaid/partial
    FOR v_fees IN
        SELECT mf.*, m.member_id, m.full_name, m.phone, m.email
        FROM public.membership_fees mf
        JOIN public.members m ON m.id = mf.member_id
        WHERE mf.id = ANY(p_fee_ids)
        FOR UPDATE
    LOOP
        IF v_member_id IS NULL THEN
            v_member_id := v_fees.member_id;
        ELSIF v_member_id != v_fees.member_id THEN
            RAISE EXCEPTION 'All selected fees must belong to the same member';
        END IF;

        IF v_fees.status NOT IN ('unpaid', 'overdue', 'partial') THEN
            RAISE EXCEPTION 'Fee for % is already paid and cannot be selected again', to_char(v_fees.billing_month, 'Month YYYY');
        END IF;

        v_total_amount := v_total_amount + (v_fees.amount_minor - v_fees.paid_amount_minor);
        v_fee_ids := v_fee_ids || v_fees.id;
        v_billing_months := v_billing_months || to_char(v_fees.billing_month, 'Month YYYY');

        -- Track the latest billing month being paid
        IF v_last_paid_month IS NULL OR v_fees.billing_month > v_last_paid_month THEN
            v_last_paid_month := v_fees.billing_month;
        END IF;

        -- Build fee data for invoice description
        v_fee_data := v_fee_data || jsonb_build_object(
            'fee_id', v_fees.id,
            'billing_month', v_fees.billing_month,
            'amount_minor', v_fees.amount_minor,
            'paid_amount_minor', v_fees.paid_amount_minor,
            'outstanding_minor', v_fees.amount_minor - v_fees.paid_amount_minor
        );
    END LOOP;

    IF v_total_amount <= 0 THEN
        RAISE EXCEPTION 'No outstanding amount to pay';
    END IF;

    -- Generate invoice number
    v_year := EXTRACT(YEAR FROM v_today)::int;
    PERFORM pg_advisory_xact_lock(20260922, 2);
    INSERT INTO public.invoice_number_sequences(sequence_year, last_number)
    VALUES (v_year, 1)
    ON CONFLICT (sequence_year) DO UPDATE SET last_number = public.invoice_number_sequences.last_number + 1, updated_at = now() RETURNING last_number INTO v_seq;
    v_number := v_prefix || '-' || v_year || '-' || lpad(v_seq::text, greatest(6, length(v_seq::text)), '0');

    -- Check for duplicate invoice number
    IF EXISTS (SELECT 1 FROM public.invoices WHERE lower(btrim(invoice_number)) = lower(v_number)) THEN
        -- Retry with next sequence
        INSERT INTO public.invoice_number_sequences(sequence_year, last_number)
        VALUES (v_year, v_seq + 1)
        ON CONFLICT (sequence_year) DO UPDATE SET last_number = public.invoice_number_sequences.last_number + 1, updated_at = now() RETURNING last_number INTO v_seq;
        v_number := v_prefix || '-' || v_year || '-' || lpad(v_seq::text, greatest(6, length(v_seq::text)), '0');
    END IF;

    -- Create the invoice
    INSERT INTO public.invoices (
        invoice_number,
        member_ref,
        customer_name,
        customer_phone,
        customer_email,
        billing_date,
        due_date,
        currency_code,
        discount_minor,
        tax_enabled,
        tax_label,
        tax_rate_basis_points,
        notes
    ) VALUES (
        v_number,
        v_member_id,
        (SELECT full_name FROM public.members WHERE id = v_member_id),
        (SELECT phone FROM public.members WHERE id = v_member_id),
        (SELECT email FROM public.members WHERE id = v_member_id),
        v_today,
        v_today,
        v_settings.currency_code,
        0,
        v_settings.tax_enabled,
        v_settings.tax_label,
        v_settings.tax_rate_basis_points,
        p_notes
    ) RETURNING id INTO v_invoice_id;

    -- Create invoice items for each fee period
    FOR v_fees IN
        SELECT * FROM public.membership_fees WHERE id = ANY(p_fee_ids) ORDER BY billing_month
    LOOP
        INSERT INTO public.invoice_items (
            invoice_id,
            item_type,
            customer_type,
            product_id,
            variant_id,
            description,
            quantity,
            unit_price_minor,
            discount_minor,
            tax_minor,
            line_total_minor,
            sort_order
        ) VALUES (
            v_invoice_id,
            'membership',
            NULL,
            NULL,
            NULL,
            to_char(v_fees.billing_month, 'Month YYYY') || ' Membership Fee',
            1,
            v_fees.amount_minor - v_fees.paid_amount_minor,
            0,
            0,
            v_fees.amount_minor - v_fees.paid_amount_minor,
            0
        );
    END LOOP;

    -- Add tax to last item if tax enabled
    IF v_settings.tax_enabled AND v_settings.tax_rate_basis_points > 0 THEN
        UPDATE public.invoice_items
        SET tax_minor = round((v_total_amount::numeric * v_settings.tax_rate_basis_points) / 10000)::bigint,
            line_total_minor = line_total_minor + round((v_total_amount::numeric * v_settings.tax_rate_basis_points) / 10000)::bigint
        WHERE id = (
            SELECT id FROM public.invoice_items
            WHERE invoice_id = v_invoice_id
            ORDER BY sort_order DESC
            LIMIT 1
        );
        v_total_amount := v_total_amount + round((v_total_amount::numeric * v_settings.tax_rate_basis_points) / 10000)::bigint;
    END IF;

    -- Update invoice totals
    UPDATE public.invoices
    SET subtotal_minor = v_total_amount - CASE WHEN v_settings.tax_enabled THEN round((v_total_amount::numeric * v_settings.tax_rate_basis_points) / 10000)::bigint ELSE 0 END,
        tax_minor = CASE WHEN v_settings.tax_enabled THEN round((v_total_amount::numeric * v_settings.tax_rate_basis_points) / 10000)::bigint ELSE 0 END,
        total_minor = v_total_amount,
        balance_minor = v_total_amount
    WHERE id = v_invoice_id;

    -- Mark selected fees as paid
    UPDATE public.membership_fees
    SET paid_amount_minor = amount_minor,
        status = 'paid',
        paid_at = now(),
        paid_by = auth.uid(),
        invoice_id = v_invoice_id,
        updated_at = now()
    WHERE id = ANY(p_fee_ids);

    -- Record the payment
    INSERT INTO public.invoice_payments (
        invoice_id,
        amount_minor,
        payment_method,
        payment_date,
        reference,
        notes
    ) VALUES (
        v_invoice_id,
        v_total_amount,
        p_payment_method,
        COALESCE(p_payment_date, v_today),
        p_reference,
        p_notes
    );

    -- Update invoice as issued
    UPDATE public.invoices
    SET invoice_status = 'issued',
        payment_status = 'paid',
        paid_minor = v_total_amount,
        balance_minor = 0,
        inventory_applied_at = now(),
        updated_by = auth.uid()
    WHERE id = v_invoice_id;

    -- Update member's payment_due_date to next month after last paid month
    UPDATE public.members
    SET payment_due_date = public.add_months_preserving_day(v_last_paid_month, 1),
        payment_status = CASE
            WHEN EXISTS (
                SELECT 1 FROM public.membership_fees
                WHERE member_id = v_member_id AND status IN ('unpaid', 'overdue', 'partial')
            ) THEN 'unpaid'
            ELSE 'paid'
        END,
        updated_at = now()
    WHERE id = v_member_id;

    -- Update invoice_number_sequences if needed
    UPDATE public.invoice_number_sequences
    SET last_number = GREATEST(last_number, v_seq), updated_at = now()
    WHERE sequence_year = v_year;

    RETURN jsonb_build_object(
        'invoice_id', v_invoice_id,
        'invoice_number', v_number,
        'total_amount_minor', v_total_amount,
        'paid_months', v_billing_months,
        'next_due_date', public.add_months_preserving_day(v_last_paid_month, 1),
        'member_id', v_member_id
    );
END $$;

-- Function to get member's membership fee details for attendance drawer
CREATE OR REPLACE FUNCTION public.get_member_membership_fee_status(p_member_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_result jsonb;
BEGIN
    SELECT jsonb_build_object(
        'has_outstanding', EXISTS (
            SELECT 1 FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
        ),
        'outstanding_fees', (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', id,
                    'billing_month', billing_month,
                    'amount_minor', amount_minor,
                    'paid_amount_minor', paid_amount_minor,
                    'outstanding_minor', amount_minor - paid_amount_minor,
                    'status', status,
                    'due_date', due_date,
                    'paid_at', paid_at,
                    'invoice_id', invoice_id
                ) ORDER BY billing_month
            ) FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
        ),
        'paid_fees', (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', id,
                    'billing_month', billing_month,
                    'amount_minor', amount_minor,
                    'paid_amount_minor', paid_amount_minor,
                    'status', status,
                    'due_date', due_date,
                    'paid_at', paid_at
                ) ORDER BY billing_month DESC
            ) FROM public.membership_fees
            WHERE member_id = p_member_id AND status = 'paid'
            LIMIT 12
        ),
        'summary', public.get_membership_fee_summary(p_member_id)
    ) INTO v_result;

    RETURN v_result;
END $$;

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION public.set_membership_fees_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END $$;

CREATE TRIGGER membership_fees_updated_at
    BEFORE UPDATE ON public.membership_fees
    FOR EACH ROW EXECUTE FUNCTION public.set_membership_fees_updated_at();

-- Grant permissions
GRANT ALL ON TABLE public.membership_fees TO anon;
GRANT ALL ON TABLE public.membership_fees TO authenticated;
GRANT ALL ON TABLE public.membership_fees TO service_role;
GRANT ALL ON SEQUENCE public.membership_fees_id_seq TO anon;
GRANT ALL ON SEQUENCE public.membership_fees_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.membership_fees_id_seq TO service_role;

GRANT EXECUTE ON FUNCTION public.next_month_first_day(date) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_months_preserving_day(date, integer) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.initialize_membership_fees(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_membership_fee_payment(bigint, bigint, text, date, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_membership_fee_payment_multi(bigint[], text, date, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.update_overdue_membership_fees() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_membership_fee_summary(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_member_membership_fee_status(bigint) TO anon, authenticated, service_role;

-- Trigger to automatically initialize membership fees for new members
CREATE OR REPLACE FUNCTION public.on_member_created()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    -- Initialize membership fees for the new member
    PERFORM public.initialize_membership_fees(NEW.id);
    RETURN NEW;
END $$;

CREATE TRIGGER member_created_initialize_fees
    AFTER INSERT ON public.members
    FOR EACH ROW EXECUTE FUNCTION public.on_member_created();