-- Import Logs Table for Legacy Migration Tracking
CREATE TABLE IF NOT EXISTS public.import_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    file_name text NOT NULL,
    import_date timestamp with time zone NOT NULL,
    members_found integer NOT NULL DEFAULT 0,
    members_imported integer NOT NULL DEFAULT 0,
    memberships_imported integer NOT NULL DEFAULT 0,
    bills_imported integer NOT NULL DEFAULT 0,
    warnings integer NOT NULL DEFAULT 0,
    errors integer NOT NULL DEFAULT 0,
    skipped_records integer NOT NULL DEFAULT 0,
    preserved_in_notes integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'completed',
    error_details text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT import_logs_status_check CHECK (status IN ('completed', 'failed', 'partial'))
);

ALTER TABLE public.import_logs OWNER TO postgres;

CREATE INDEX IF NOT EXISTS import_logs_import_date_idx ON public.import_logs (import_date DESC);

ALTER TABLE public.import_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "import_logs_select_admin" ON public.import_logs FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "import_logs_insert_admin" ON public.import_logs FOR INSERT TO authenticated WITH CHECK (public.is_admin());

GRANT ALL ON TABLE public.import_logs TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.import_logs_id_seq TO anon, authenticated, service_role;

-- Add legacy tracking columns to members table if not exists
ALTER TABLE public.members 
ADD COLUMN IF NOT EXISTS legacy_register_id bigint,
ADD COLUMN IF NOT EXISTS legacy_source text;

CREATE INDEX IF NOT EXISTS members_legacy_idx ON public.members (legacy_source, legacy_register_id) WHERE legacy_source IS NOT NULL;

-- Add legacy tracking columns to membership_fees table if not exists
ALTER TABLE public.membership_fees
ADD COLUMN IF NOT EXISTS legacy_officeregister_id bigint,
ADD COLUMN IF NOT EXISTS legacy_source text;

CREATE INDEX IF NOT EXISTS membership_fees_legacy_idx ON public.membership_fees (legacy_source, legacy_officeregister_id) WHERE legacy_source IS NOT NULL;

-- Add legacy tracking columns to invoices table if not exists
ALTER TABLE public.invoices
ADD COLUMN IF NOT EXISTS legacy_bill_id bigint,
ADD COLUMN IF NOT EXISTS legacy_source text;

CREATE INDEX IF NOT EXISTS invoices_legacy_idx ON public.invoices (legacy_source, legacy_bill_id) WHERE legacy_source IS NOT NULL;

-- Add legacy tracking columns to invoice_payments table if not exists
ALTER TABLE public.invoice_payments
ADD COLUMN IF NOT EXISTS legacy_bill_id bigint,
ADD COLUMN IF NOT EXISTS legacy_source text;

CREATE INDEX IF NOT EXISTS invoice_payments_legacy_idx ON public.invoice_payments (legacy_source, legacy_bill_id) WHERE legacy_source IS NOT NULL;