-- Add is_active column and status history tracking for members

-- Add is_active column to members table
ALTER TABLE public.members
ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT false;

-- Add timestamp columns for activation/deactivation audit
ALTER TABLE public.members
ADD COLUMN IF NOT EXISTS activated_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS deactivated_at timestamp with time zone;

-- Create index for filtering active members
CREATE INDEX IF NOT EXISTS members_is_active_idx ON public.members (is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS members_is_active_all_idx ON public.members (is_active);

-- Create member_status_history table for audit trail
CREATE TABLE IF NOT EXISTS public.member_status_history (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    status text NOT NULL CHECK (status IN ('active', 'inactive')),
    changed_by uuid,
    changed_at timestamp with time zone DEFAULT now() NOT NULL,
    notes text,
    CONSTRAINT member_status_history_pkey PRIMARY KEY (id)
);

ALTER TABLE public.member_status_history OWNER TO postgres;

CREATE INDEX IF NOT EXISTS member_status_history_member_id_idx ON public.member_status_history (member_id);
CREATE INDEX IF NOT EXISTS member_status_history_changed_at_idx ON public.member_status_history (changed_at DESC);

ALTER TABLE public.member_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "member_status_history_select_admin" ON public.member_status_history FOR SELECT TO authenticated USING (public.is_admin());
CREATE POLICY "member_status_history_insert_admin" ON public.member_status_history FOR INSERT TO authenticated WITH CHECK (public.is_admin());

GRANT ALL ON TABLE public.member_status_history TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.member_status_history_id_seq TO anon, authenticated, service_role;

-- Create function to update member status with history tracking
CREATE OR REPLACE FUNCTION public.set_member_active_status(
    p_member_id bigint,
    p_is_active boolean,
    p_changed_by uuid DEFAULT NULL,
    p_notes text DEFAULT NULL
)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_member RECORD;
    v_old_status text;
    v_new_status text;
BEGIN
    -- Verify admin access
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Admin access required';
    END IF;

    -- Get current member
    SELECT * INTO v_member FROM public.members WHERE id = p_member_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Member not found';
    END IF;

    -- No change needed
    IF v_member.is_active = p_is_active THEN
        RETURN;
    END IF;

    v_old_status := CASE WHEN v_member.is_active THEN 'active' ELSE 'inactive' END;
    v_new_status := CASE WHEN p_is_active THEN 'active' ELSE 'inactive' END;

    -- Update member status
    IF p_is_active THEN
        UPDATE public.members
        SET is_active = true,
            activated_at = now(),
            deactivated_at = NULL,
            updated_at = now()
        WHERE id = p_member_id;
    ELSE
        UPDATE public.members
        SET is_active = false,
            deactivated_at = now(),
            activated_at = NULL,
            updated_at = now()
        WHERE id = p_member_id;
    END IF;

    -- Record status change in history
    INSERT INTO public.member_status_history (member_id, status, changed_by, notes)
    VALUES (p_member_id, v_new_status, p_changed_by, p_notes);
END $$;

ALTER FUNCTION public.set_member_active_status(bigint, boolean, uuid, text) OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.set_member_active_status(bigint, boolean, uuid, text) TO anon, authenticated, service_role;

-- No trigger to auto-set is_active; application controls it explicitly
-- New members created via admin panel: is_active = true (set by application)
-- Members imported from legacy SQL: is_active = false (set by application)
-- Update existing members to be inactive (default for legacy data)
UPDATE public.members SET is_active = false WHERE is_active IS NULL;

-- Update functions to respect is_active status
-- 1. Update initialize_membership_fees to skip inactive members
DROP FUNCTION IF EXISTS public.initialize_membership_fees(bigint);

CREATE OR REPLACE FUNCTION public.initialize_membership_fees(p_member_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_member RECORD;
    v_start_date date;
    v_end_date date;
    v_current_month date;
    v_amount_minor bigint;
    v_plan_price text;
    v_currency_code text;
    v_month_diff integer;
BEGIN
    -- Get member details
    SELECT m.*, s.currency_code
    INTO v_member
    FROM public.members m
    CROSS JOIN public.admin_settings s
    WHERE m.id = p_member_id AND s.id = 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Member not found';
    END IF;

    -- Skip if member is inactive
    IF NOT v_member.is_active THEN
        RETURN;
    END IF;

    -- Get plan price from pricing_items
    SELECT price INTO v_plan_price
    FROM public.pricing_items
    WHERE kind = 'plan' AND title ILIKE v_member.membership_type AND is_active = true
    ORDER BY sort_order LIMIT 1;

    IF v_plan_price IS NOT NULL THEN
        v_amount_minor := regexp_replace(v_plan_price, '[^\d.]', '', 'g')::numeric * 100;
    ELSE
        v_amount_minor := 0;
    END IF;

    v_currency_code := v_member.currency_code;
    v_start_date := v_member.start_date;
    v_end_date := v_member.end_date;

    IF v_start_date IS NULL THEN
        v_start_date := v_member.created_at::date;
    END IF;

    IF v_end_date IS NULL THEN
        v_end_date := date_trunc('month', public.get_nepal_today_ad())::date;
    END IF;

    v_current_month := date_trunc('month', v_start_date)::date;

    WHILE v_current_month <= date_trunc('month', v_end_date)::date LOOP
        v_month_diff := (EXTRACT(YEAR FROM v_current_month) - EXTRACT(YEAR FROM v_start_date)) * 12
                        + (EXTRACT(MONTH FROM v_current_month) - EXTRACT(MONTH FROM v_start_date));

        INSERT INTO public.membership_fees (member_id, billing_month, amount_minor, currency_code, status, due_date)
        VALUES (
            p_member_id,
            v_current_month,
            v_amount_minor,
            v_currency_code,
            CASE WHEN v_current_month <= date_trunc('month', public.get_nepal_today_ad())::date THEN 'unpaid' ELSE 'unpaid' END,
            public.add_months_preserving_day(v_start_date, v_month_diff)
        )
        ON CONFLICT (member_id, billing_month) DO NOTHING;

        v_current_month := public.next_month_first_day(v_current_month);
    END LOOP;

    UPDATE public.members
    SET payment_due_date = (
        SELECT MIN(due_date) FROM public.membership_fees
        WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
    )
    WHERE id = p_member_id;
END $$;

-- 2. Update update_overdue_membership_fees to skip inactive members
DROP FUNCTION IF EXISTS public.update_overdue_membership_fees();

CREATE OR REPLACE FUNCTION public.update_overdue_membership_fees()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_today date := public.get_nepal_today_ad();
    v_count integer := 0;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Admin access required';
    END IF;

    UPDATE public.membership_fees mf
    SET status = 'overdue',
        updated_at = now()
    FROM public.members m
    WHERE mf.member_id = m.id
      AND m.is_active = true
      AND mf.status IN ('unpaid', 'partial')
      AND mf.due_date < v_today;

    GET DIAGNOSTICS v_count = ROW_COUNT;

    UPDATE public.members m
    SET payment_status = 'overdue',
        updated_at = now()
    WHERE EXISTS (
        SELECT 1 FROM public.membership_fees mf
        WHERE mf.member_id = m.id AND mf.status = 'overdue'
    )
    AND m.is_active = true
    AND m.payment_status != 'overdue'
    AND m.deleted_at IS NULL;

    RETURN v_count;
END $$;

-- 3. Update get_member_membership_fee_status to return empty for inactive members
DROP FUNCTION IF EXISTS public.get_member_membership_fee_status(bigint);

CREATE OR REPLACE FUNCTION public.get_member_membership_fee_status(p_member_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_result jsonb;
    v_member RECORD;
BEGIN
    SELECT * INTO v_member FROM public.members WHERE id = p_member_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Member not found';
    END IF;

    -- Return empty for inactive members
    IF NOT v_member.is_active THEN
        RETURN jsonb_build_object(
            'has_outstanding', false,
            'outstanding_fees', '[]'::jsonb,
            'paid_fees', '[]'::jsonb,
            'summary', jsonb_build_object(
                'total_due', 0, 'total_paid', 0, 'overdue_count', 0, 'unpaid_count', 0,
                'partial_count', 0, 'paid_count', 0, 'next_due_date', null,
                'next_due_amount', null, 'next_due_month', null, 'currency_code', 'NPR'
            )
        );
    END IF;

    SELECT jsonb_build_object(
        'has_outstanding', EXISTS (
            SELECT 1 FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
        ),
        'outstanding_fees', (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', id,
                    'billing_month', billing_month,
                    'amount_minor', amount_minor,
                    'paid_amount_minor', paid_amount_minor,
                    'outstanding_minor', amount_minor - paid_amount_minor,
                    'status', status,
                    'due_date', due_date,
                    'paid_at', paid_at,
                    'invoice_id', invoice_id
                ) ORDER BY billing_month
            ) FROM public.membership_fees
            WHERE member_id = p_member_id AND status IN ('unpaid', 'overdue', 'partial')
        ),
        'paid_fees', (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', id,
                    'billing_month', billing_month,
                    'amount_minor', amount_minor,
                    'paid_amount_minor', paid_amount_minor,
                    'status', status,
                    'due_date', due_date,
                    'paid_at', paid_at
                ) ORDER BY billing_month DESC
            ) FROM public.membership_fees
            WHERE member_id = p_member_id AND status = 'paid'
            LIMIT 12
        ),
        'summary', public.get_membership_fee_summary(p_member_id)
    ) INTO v_result;

    RETURN v_result;
END $$;

-- Trigger to prevent attendance recording for inactive members
CREATE OR REPLACE FUNCTION public.prevent_inactive_attendance()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_member_active boolean;
BEGIN
    SELECT is_active INTO v_member_active FROM public.members WHERE id = NEW.member_ref;
    IF NOT v_member_active THEN
        RAISE EXCEPTION 'Cannot record attendance for inactive member';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER attendance_prevent_inactive
    BEFORE INSERT ON public.attendance_records
    FOR EACH ROW EXECUTE FUNCTION public.prevent_inactive_attendance();

-- Update record_membership_fee_payment to check is_active
DROP FUNCTION IF EXISTS public.record_membership_fee_payment(
    bigint, bigint, text, date, text, text
);

CREATE OR REPLACE FUNCTION public.record_membership_fee_payment(
    p_fee_id bigint,
    p_amount_minor bigint,
    p_payment_method text,
    p_payment_date date DEFAULT NULL,
    p_reference text DEFAULT NULL,
    p_notes text DEFAULT NULL
)
RETURNS public.membership_fees LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
    v_fee RECORD;
    v_new_paid_amount bigint;
    v_new_status text;
    v_member_active boolean;
BEGIN
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Admin access required';
    END IF;

    IF p_amount_minor <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be positive';
    END IF;

    SELECT mf.*, m.is_active INTO v_fee
    FROM public.membership_fees mf
    JOIN public.members m ON m.id = mf.member_id
    WHERE mf.id = p_fee_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Membership fee not found';
    END IF;

    -- Prevent payment for inactive member's fees
    IF NOT v_member_active THEN
        RAISE EXCEPTION 'Cannot record payment for inactive member';
    END IF;

    IF v_fee.paid_amount_minor + p_amount_minor > v_fee.amount_minor THEN
        RAISE EXCEPTION 'Payment exceeds outstanding amount';
    END IF;

    v_new_paid_amount := v_fee.paid_amount_minor + p_amount_minor;
    v_new_status := CASE
        WHEN v_new_paid_amount >= v_fee.amount_minor THEN 'paid'
        WHEN v_new_paid_amount > 0 THEN 'partial'
        ELSE v_fee.status
    END;

    UPDATE public.membership_fees
    SET paid_amount_minor = v_new_paid_amount,
        status = v_new_status,
        paid_at = CASE WHEN v_new_status = 'paid' THEN now() ELSE paid_at END,
        paid_by = CASE WHEN v_new_status = 'paid' THEN auth.uid() ELSE paid_by END,
        updated_at = now()
    WHERE id = p_fee_id
    RETURNING * INTO v_fee;

    UPDATE public.members
    SET payment_due_date = (
        SELECT MIN(due_date) FROM public.membership_fees
        WHERE member_id = v_fee.member_id AND status IN ('unpaid', 'overdue', 'partial')
    ),
    payment_status = CASE
        WHEN EXISTS (
            SELECT 1 FROM public.membership_fees
            WHERE member_id = v_fee.member_id AND status IN ('unpaid', 'overdue', 'partial')
        ) THEN 'unpaid'
        ELSE 'paid'
    END,
    updated_at = now()
    WHERE id = v_fee.member_id;

    RETURN v_fee;
END $$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION public.set_member_active_status(bigint, boolean, uuid, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.initialize_membership_fees(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.update_overdue_membership_fees() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_member_membership_fee_status(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_membership_fee_payment(bigint, bigint, text, date, text, text) TO anon, authenticated, service_role;